FROM mcr.microsoft.com/devcontainers/go:1.24-bookworm

ENV DEBIAN_FRONTEND=noninteractive

RUN echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/isolate.asc] http://www.ucw.cz/isolate/debian/ bookworm-isolate main" > /etc/apt/sources.list.d/isolate.list && \
    curl https://www.ucw.cz/isolate/debian/signing-key.asc >/etc/apt/keyrings/isolate.asc && \
    apt update && apt install -y --no-install-recommends isolate && \
    rm -rf /var/lib/apt/lists/*

COPY isolate.conf /etc/isolate