FROM mcr.microsoft.com/devcontainers/go:1.25-trixie

RUN echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/isolate.asc] http://www.ucw.cz/isolate/debian/ bookworm-isolate main" > /etc/apt/sources.list.d/isolate.list && \
    curl https://www.ucw.cz/isolate/debian/signing-key.asc >/etc/apt/keyrings/isolate.asc && \
    apt update && apt install -y --no-install-recommends isolate && \
    rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/isolate /usr/local/bin/isolate
RUN ln -s /usr/bin/bash /usr/local/bin/bash